server:
  port: 8083

philips:
  tenants:
    -
      tenantId: HSC
      asyncConsumers: 1
      syncConsumers: 3
    - 
      tenantId: HSI
      asyncConsumers: 2
      syncConsumers: 4

spring:
  rabbitmq:
    addresses: rmq-f123cffe.svc-1.sa1.cluster.hsdp.io:5672
    username: admin
    password: DebS0uFxl7BWeTSf
    cache:
      connection:
        mode: channel

debug: false