server:
  port: 8083
spring:
  rabbitmq:
    addresses: localhost:5672
    username: chinainbox
    password: chinainbox
    virtual-host: chinainbox
    cache:
      connection:
        mode: connection
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
debug: false
philips:
  tenants:
    -
      tenantId: HSC
      asyncConsumers: 1
      syncConsumers: 3
    - 
      tenantId: HSI
      asyncConsumers: 2
      syncConsumers: 4      